# Form implementation generated from reading ui file '.\Main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon,QFont, QPixmap, QMovie
from PyQt6.QtCore import QSize
from PyQt6.QtWidgets import QTableWidgetItem
# from persiantools import jdatetime

# import mysql.connector as mc
# import mysql.connector
# from Data_Base import *

class Ui_MainWindow(object):
    # _engine = create_engine('mysql+pymysql://admin:1234@localhost/test_setstatus')
    # _base = declarative_base()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 720)
        MainWindow.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(92, 0))
        self.frame.setMaximumSize(QtCore.QSize(92, 16777215))
        self.frame.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Btn_Menu = QtWidgets.QPushButton(self.frame)
        self.Btn_Menu.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_Menu.setStyleSheet("QPushButton {    \n"
                                    "    background-position: left center;\n"
                                    "    background-repeat: no-repeat;\n"
                                    "    border: none;\n"
                                    "    background-color: rgb(27, 29, 35);\n"
                                    "    text-align: left;\n"
                                    "    padding-left: 45px;\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: rgb(33, 37, 43);\n"
                                    "    border-right: 5px solid rgb(44, 49, 60);\n"
                                    "}\n"
                                    "QPushButton:pressed {    \n"
                                    "    background-color: rgb(85, 170, 255);\n"
                                    "    border-right: 5px solid rgb(44, 49, 60);\n"
                                    "}")
        self.Btn_Menu.setText("")
        self.Btn_Menu.setIconSize(QtCore.QSize(16, 16))
        self.Btn_Menu.setObjectName("Btn_Menu")
        self.verticalLayout_3.addWidget(self.Btn_Menu)
        self.Btn_Home = QtWidgets.QPushButton(self.frame)
        self.Btn_Home.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_Home.setStyleSheet("QPushButton {    \n"
                                    "    background-position: left center;\n"
                                    "    background-repeat: no-repeat;\n"
                                    "    border: none;\n"
                                    "    background-color: rgb(27, 29, 35);\n"
                                    "    text-align: left;\n"
                                    "    padding-left: 45px;\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: rgb(33, 37, 43);\n"
                                    "    border-right: 5px solid rgb(44, 49, 60);\n"
                                    "}\n"
                                    "QPushButton:pressed {    \n"
                                    "    background-color: rgb(85, 170, 255);\n"
                                    "    border-right: 5px solid rgb(44, 49, 60);\n"
                                    "}")
        self.Btn_Home.setText("")
        self.Btn_Home.setObjectName("Btn_Home")
        self.verticalLayout_3.addWidget(self.Btn_Home)
        self.Btn_classList = QtWidgets.QPushButton(self.frame)
        self.Btn_classList.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_classList.setStyleSheet("QPushButton {    \n"
                                         "    background-position: left center;\n"
                                         "    background-repeat: no-repeat;\n"
                                         "    border: none;\n"
                                         "    background-color: rgb(27, 29, 35);\n"
                                         "    text-align: left;\n"
                                         "    padding-left: 45px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(33, 37, 43);\n"
                                         "    border-right: 5px solid rgb(44, 49, 60);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: rgb(85, 170, 255);\n"
                                         "    border-right: 5px solid rgb(44, 49, 60);\n"
                                         "}")
        self.Btn_classList.setText("")
        self.Btn_classList.setObjectName("Btn_classList")
        self.verticalLayout_3.addWidget(self.Btn_classList)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_Picture = QtWidgets.QLabel(self.frame)
        self.label_Picture.setMinimumSize(QtCore.QSize(60, 60))
        self.label_Picture.setMaximumSize(QtCore.QSize(60, 60))
        self.label_Picture.setStyleSheet("QLabel {\n"
                                         "    \n"
                                         "\n"
                                         "}")
        self.label_Picture.setText("")
        self.label_Picture.setObjectName("label_Picture")
        self.horizontalLayout_9.addWidget(self.label_Picture)
        spacerItem2 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.Btn_Settings = QtWidgets.QPushButton(self.frame)
        self.Btn_Settings.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_Settings.setStyleSheet("QPushButton {    \n"
                                        "    background-position: left center;\n"
                                        "    background-repeat: no-repeat;\n"
                                        "    border: none;\n"
                                        "    background-color: rgb(27, 29, 35);\n"
                                        "    text-align: left;\n"
                                        "    padding-left: 45px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(33, 37, 43);\n"
                                        "    border-right: 5px solid rgb(44, 49, 60);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "    border-right: 5px solid rgb(44, 49, 60);\n"
                                        "}")
        self.Btn_Settings.setText("")
        self.Btn_Settings.setIconSize(QtCore.QSize(48, 48))
        self.Btn_Settings.setObjectName("Btn_Settings")
        self.verticalLayout_2.addWidget(self.Btn_Settings)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_11.addWidget(self.frame)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_Application = QtWidgets.QLabel(self.frame_4)
        self.label_Application.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_Application.setFont(font)
        self.label_Application.setStyleSheet("color: rgb(98, 103, 111);\n"
                                             "background: transparent;\n"
                                             "")
        self.label_Application.setObjectName("label_Application")
        self.horizontalLayout_10.addWidget(self.label_Application)
        spacerItem5 = QtWidgets.QSpacerItem(723, 40, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.Btn_min = QtWidgets.QPushButton(self.frame_4)
        self.Btn_min.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_min.setStyleSheet("QPushButton {    \n"
                                   "    border: none;\n"
                                   "    background-color: transparent;\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: rgb(52, 59, 72);\n"
                                   "}\n"
                                   "QPushButton:pressed {    \n"
                                   "    background-color: rgb(85, 170, 255);\n"
                                   "}")
        self.Btn_min.setText("")
        self.Btn_min.setObjectName("Btn_min")
        self.horizontalLayout_10.addWidget(self.Btn_min)
        self.Btn_max = QtWidgets.QPushButton(self.frame_4)
        self.Btn_max.setMinimumSize(QtCore.QSize(16, 16))
        self.Btn_max.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_max.setStyleSheet("QPushButton {    \n"
                                   "    border: none;\n"
                                   "    background-color: transparent;\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: rgb(52, 59, 72);\n"
                                   "}\n"
                                   "QPushButton:pressed {    \n"
                                   "    background-color: rgb(85, 170, 255);\n"
                                   "}")
        self.Btn_max.setText("")
        self.Btn_max.setObjectName("Btn_max")
        self.horizontalLayout_10.addWidget(self.Btn_max)
        self.Btn_close = QtWidgets.QPushButton(self.frame_4)
        self.Btn_close.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_close.setStyleSheet("QPushButton {    \n"
                                     "    border: none;\n"
                                     "    background-color: transparent;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: rgb(52, 59, 72);\n"
                                     "}\n"
                                     "QPushButton:pressed {    \n"
                                     "    background-color: rgb(85, 170, 255);\n"
                                     "}")
        self.Btn_close.setText("")
        self.Btn_close.setObjectName("Btn_close")
        self.horizontalLayout_10.addWidget(self.Btn_close)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Home = QtWidgets.QWidget()
        self.page_Home.setObjectName("page_Home")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_Home)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_Home = QtWidgets.QLabel(self.page_Home)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        self.label_Home.setFont(font)
        self.label_Home.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(40, 44, 52);\n"
                                      "")
        self.label_Home.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Home.setObjectName("label_Home")
        self.verticalLayout_7.addWidget(self.label_Home)
        self.stackedWidget.addWidget(self.page_Home)
        self.page_Setting = QtWidgets.QWidget()
        self.page_Setting.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.page_Setting.setObjectName("page_Setting")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_Setting)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget_changeInfo = QtWidgets.QTabWidget(self.page_Setting)
        self.tabWidget_changeInfo.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.tabWidget_changeInfo.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.tabWidget_changeInfo.setAcceptDrops(False)
        self.tabWidget_changeInfo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget_changeInfo.setStyleSheet("border-bottom: none;\n"
                                                "color: rgb(191, 191, 191);")
        self.tabWidget_changeInfo.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget_changeInfo.setDocumentMode(True)
        self.tabWidget_changeInfo.setTabsClosable(False)
        self.tabWidget_changeInfo.setMovable(False)
        self.tabWidget_changeInfo.setTabBarAutoHide(True)
        self.tabWidget_changeInfo.setObjectName("tabWidget_changeInfo")
        self.Add_Professor = QtWidgets.QWidget()
        self.Add_Professor.setObjectName("Add_Professor")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Add_Professor)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.Add_Professor)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Btn_showList_add = QtWidgets.QPushButton(self.frame_5)
        self.Btn_showList_add.setStyleSheet("QPushButton:hover {    \n"
                                            "    color: rgb(210, 210, 210);\n"
                                            "    background-color: rgb(44, 49, 60);\n"
                                            "}\n"
                                            "QPushButton\n"
                                            "{\n"
                                            "\n"
                                            "    border-radius: 5px;\n"
                                            "    padding: 5px;\n"
                                            "    color: rgb(85, 170, 255);\n"
                                            "    background-color: rgb(52, 58, 71);\n"
                                            "}\n"
                                            "QPushButton:pressed {    \n"
                                            "    background-color: rgba(85, 170, 255,0.5);\n"
                                            "    \n"
                                            "}")
        self.Btn_showList_add.setObjectName("Btn_showList_add")
        self.horizontalLayout_17.addWidget(self.Btn_showList_add)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.verticalLayout_12.addLayout(self.verticalLayout_15)
        self.tableWidget_add = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_add.setStyleSheet("color: rgb(255, 0, 0);")
        self.tableWidget_add.setObjectName("tableWidget_add")
        self.tableWidget_add.setColumnCount(5)
        self.tableWidget_add.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_add.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_add.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_add.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_add.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_add.setHorizontalHeaderItem(4, item)
        self.tableWidget_add.horizontalHeader().setDefaultSectionSize(175)
        self.verticalLayout_12.addWidget(self.tableWidget_add)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.Add_Professor)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.lineEdit_namePro_add = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_namePro_add.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                "border:1px solid rgba(0, 0, 0, 0);\n"
                                                "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                "color:rgb(255, 255, 255);\n"
                                                "padding-bottom:7px")
        self.lineEdit_namePro_add.setObjectName("lineEdit_namePro_add")
        self.verticalLayout_8.addWidget(self.lineEdit_namePro_add)
        self.horizontalLayout_14.addWidget(self.frame_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.lineEdit_nameStudy_add = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_nameStudy_add.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                  "border:1px solid rgba(0, 0, 0, 0);\n"
                                                  "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                  "color:rgb(255, 255, 255);\n"
                                                  "padding-bottom:7px")
        self.lineEdit_nameStudy_add.setObjectName("lineEdit_nameStudy_add")
        self.verticalLayout_9.addWidget(self.lineEdit_nameStudy_add)
        self.horizontalLayout_14.addWidget(self.frame_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.lineEdit_Days_add = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_Days_add.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                             "border:1px solid rgba(0, 0, 0, 0);\n"
                                             "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                             "color:rgb(255, 255, 255);\n"
                                             "padding-bottom:7px")
        self.lineEdit_Days_add.setObjectName("lineEdit_Days_add")
        self.verticalLayout_10.addWidget(self.lineEdit_Days_add)
        self.horizontalLayout_14.addWidget(self.frame_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.lineEdit_time_add = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_time_add.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                             "border:1px solid rgba(0, 0, 0, 0);\n"
                                             "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                             "color:rgb(255, 255, 255);\n"
                                             "padding-bottom:7px")
        self.lineEdit_time_add.setObjectName("lineEdit_time_add")
        self.verticalLayout_11.addWidget(self.lineEdit_time_add)
        self.horizontalLayout_14.addWidget(self.frame_10)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.frame_11 = QtWidgets.QFrame(self.Add_Professor)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.Btn_Accept_add = QtWidgets.QPushButton(self.frame_11)
        self.Btn_Accept_add.setStyleSheet("QPushButton:hover {    \n"
                                          "    color: rgb(210, 210, 210);\n"
                                          "    background-color: rgb(44, 49, 60);\n"
                                          "}\n"
                                          "QPushButton\n"
                                          "{\n"
                                          "\n"
                                          "    border-radius: 5px;\n"
                                          "    padding: 5px;\n"
                                          "    color: rgb(85, 170, 255);\n"
                                          "    background-color: rgb(52, 58, 71);\n"
                                          "}\n"
                                          "QPushButton:pressed {    \n"
                                          "    background-color: rgba(85, 170, 255,0.5);\n"
                                          "    \n"
                                          "}")
        self.Btn_Accept_add.setObjectName("Btn_Accept_add")
        self.horizontalLayout_15.addWidget(self.Btn_Accept_add)
        self.verticalLayout_13.addWidget(self.frame_11)
        self.tabWidget_changeInfo.addTab(self.Add_Professor, "")
        self.remove_professor = QtWidgets.QWidget()
        self.remove_professor.setObjectName("remove_professor")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.remove_professor)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Btn_showList_rm = QtWidgets.QPushButton(self.remove_professor)
        self.Btn_showList_rm.setStyleSheet("QPushButton:hover {    \n"
                                           "    color: rgb(210, 210, 210);\n"
                                           "    background-color: rgb(44, 49, 60);\n"
                                           "}\n"
                                           "QPushButton\n"
                                           "{\n"
                                           "\n"
                                           "    border-radius: 5px;\n"
                                           "    padding: 5px;\n"
                                           "    color: rgb(85, 170, 255);\n"
                                           "    background-color: rgb(52, 58, 71);\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: rgba(85, 170, 255,0.5);\n"
                                           "    \n"
                                           "}")
        self.Btn_showList_rm.setObjectName("Btn_showList_rm")
        self.horizontalLayout_16.addWidget(self.Btn_showList_rm)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.verticalLayout_14)
        self.tableWidget_rm = QtWidgets.QTableWidget(self.remove_professor)
        self.tableWidget_rm.setStyleSheet("color: rgb(255, 0, 0);")
        self.tableWidget_rm.setObjectName("tableWidget_rm")
        self.tableWidget_rm.setColumnCount(5)
        self.tableWidget_rm.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rm.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rm.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rm.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rm.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rm.setHorizontalHeaderItem(4, item)
        self.tableWidget_rm.horizontalHeader().setDefaultSectionSize(175)
        self.verticalLayout_17.addWidget(self.tableWidget_rm)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.remove_professor)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_16.addWidget(self.label_6)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit_id_rm = QtWidgets.QLineEdit(self.remove_professor)
        self.lineEdit_id_rm.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                          "border:1px solid rgba(0, 0, 0, 0);\n"
                                          "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                          "color:rgb(255, 255, 255);\n"
                                          "padding-bottom:7px")
        self.lineEdit_id_rm.setObjectName("lineEdit_id_rm")
        self.horizontalLayout_19.addWidget(self.lineEdit_id_rm)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkBox_rm = QtWidgets.QCheckBox(self.remove_professor)
        self.checkBox_rm.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_rm.setObjectName("checkBox_rm")
        self.horizontalLayout_18.addWidget(self.checkBox_rm)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem13)
        self.Btn_Accept_rm = QtWidgets.QPushButton(self.remove_professor)
        self.Btn_Accept_rm.setStyleSheet("QPushButton:hover {    \n"
                                         "    color: rgb(210, 210, 210);\n"
                                         "    background-color: rgb(44, 49, 60);\n"
                                         "}\n"
                                         "QPushButton\n"
                                         "{\n"
                                         "\n"
                                         "    border-radius: 5px;\n"
                                         "    padding: 5px;\n"
                                         "    color: rgb(85, 170, 255);\n"
                                         "    background-color: rgb(52, 58, 71);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: rgba(85, 170, 255,0.5);\n"
                                         "    \n"
                                         "}")
        self.Btn_Accept_rm.setObjectName("Btn_Accept_rm")
        self.horizontalLayout_18.addWidget(self.Btn_Accept_rm)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        self.tabWidget_changeInfo.addTab(self.remove_professor, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.Btn_showList_changeInfo = QtWidgets.QPushButton(self.tab_5)
        self.Btn_showList_changeInfo.setStyleSheet("QPushButton:hover {    \n"
                                                   "    color: rgb(210, 210, 210);\n"
                                                   "    background-color: rgb(44, 49, 60);\n"
                                                   "}\n"
                                                   "QPushButton\n"
                                                   "{\n"
                                                   "\n"
                                                   "    border-radius: 5px;\n"
                                                   "    padding: 5px;\n"
                                                   "    color: rgb(85, 170, 255);\n"
                                                   "    background-color: rgb(52, 58, 71);\n"
                                                   "}\n"
                                                   "QPushButton:pressed {    \n"
                                                   "    background-color: rgba(85, 170, 255,0.5);\n"
                                                   "    \n"
                                                   "}")
        self.Btn_showList_changeInfo.setObjectName("Btn_showList_changeInfo")
        self.horizontalLayout_20.addWidget(self.Btn_showList_changeInfo)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem14)
        self.verticalLayout_23.addLayout(self.horizontalLayout_20)
        self.tableWidget_changeInfo = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_changeInfo.setStyleSheet("color: rgb(255, 0, 0);")
        self.tableWidget_changeInfo.setObjectName("tableWidget_changeInfo")
        self.tableWidget_changeInfo.setColumnCount(5)
        self.tableWidget_changeInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_changeInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_changeInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_changeInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_changeInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_changeInfo.setHorizontalHeaderItem(4, item)
        self.tableWidget_changeInfo.horizontalHeader().setDefaultSectionSize(175)
        self.verticalLayout_23.addWidget(self.tableWidget_changeInfo)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_16 = QtWidgets.QFrame(self.tab_5)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_11 = QtWidgets.QLabel(self.frame_16)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_22.addWidget(self.label_11)
        self.lineEdit_id_changeInfo = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_id_changeInfo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                  "border:1px solid rgba(0, 0, 0, 0);\n"
                                                  "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                  "color:rgb(255, 255, 255);\n"
                                                  "padding-bottom:7px")
        self.lineEdit_id_changeInfo.setText("")
        self.lineEdit_id_changeInfo.setObjectName("lineEdit_id_changeInfo")
        self.verticalLayout_22.addWidget(self.lineEdit_id_changeInfo)
        self.horizontalLayout_21.addWidget(self.frame_16)
        spacerItem15 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem15)
        self.frame_12 = QtWidgets.QFrame(self.tab_5)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.lineEdit_namePro_changeInfo = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_namePro_changeInfo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                       "border:1px solid rgba(0, 0, 0, 0);\n"
                                                       "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                       "color:rgb(255, 255, 255);\n"
                                                       "padding-bottom:7px")
        self.lineEdit_namePro_changeInfo.setObjectName("lineEdit_namePro_changeInfo")
        self.verticalLayout_18.addWidget(self.lineEdit_namePro_changeInfo)
        self.horizontalLayout_21.addWidget(self.frame_12)
        spacerItem16 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.frame_13 = QtWidgets.QFrame(self.tab_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_19.addWidget(self.label_8)
        self.lineEdit_nameStudy_changeInfo = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_nameStudy_changeInfo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                         "border:1px solid rgba(0, 0, 0, 0);\n"
                                                         "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                         "color:rgb(255, 255, 255);\n"
                                                         "padding-bottom:7px")
        self.lineEdit_nameStudy_changeInfo.setObjectName("lineEdit_nameStudy_changeInfo")
        self.verticalLayout_19.addWidget(self.lineEdit_nameStudy_changeInfo)
        self.horizontalLayout_21.addWidget(self.frame_13)
        spacerItem17 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem17)
        self.frame_14 = QtWidgets.QFrame(self.tab_5)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_20.addWidget(self.label_9)
        self.lineEdit_Days_changeInfo = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_Days_changeInfo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                    "border:1px solid rgba(0, 0, 0, 0);\n"
                                                    "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                    "color:rgb(255, 255, 255);\n"
                                                    "padding-bottom:7px")
        self.lineEdit_Days_changeInfo.setObjectName("lineEdit_Days_changeInfo")
        self.verticalLayout_20.addWidget(self.lineEdit_Days_changeInfo)
        self.horizontalLayout_21.addWidget(self.frame_14)
        spacerItem18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem18)
        self.frame_15 = QtWidgets.QFrame(self.tab_5)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_10 = QtWidgets.QLabel(self.frame_15)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_21.addWidget(self.label_10)
        self.lineEdit_Time_changeInfo = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_Time_changeInfo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                                    "border:1px solid rgba(0, 0, 0, 0);\n"
                                                    "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                                    "color:rgb(255, 255, 255);\n"
                                                    "padding-bottom:7px")
        self.lineEdit_Time_changeInfo.setObjectName("lineEdit_Time_changeInfo")
        self.verticalLayout_21.addWidget(self.lineEdit_Time_changeInfo)
        self.horizontalLayout_21.addWidget(self.frame_15)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.checkBox_changeInfo = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_changeInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_changeInfo.setObjectName("checkBox_changeInfo")
        self.horizontalLayout_22.addWidget(self.checkBox_changeInfo)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem19)
        self.Btn_Accept_changeInfo = QtWidgets.QPushButton(self.tab_5)
        self.Btn_Accept_changeInfo.setStyleSheet("QPushButton:hover {    \n"
                                                 "    color: rgb(210, 210, 210);\n"
                                                 "    background-color: rgb(44, 49, 60);\n"
                                                 "}\n"
                                                 "QPushButton\n"
                                                 "{\n"
                                                 "\n"
                                                 "    border-radius: 5px;\n"
                                                 "    padding: 5px;\n"
                                                 "    color: rgb(85, 170, 255);\n"
                                                 "    background-color: rgb(52, 58, 71);\n"
                                                 "}\n"
                                                 "QPushButton:pressed {    \n"
                                                 "    background-color: rgba(85, 170, 255,0.5);\n"
                                                 "    \n"
                                                 "}")
        self.Btn_Accept_changeInfo.setObjectName("Btn_Accept_changeInfo")
        self.horizontalLayout_22.addWidget(self.Btn_Accept_changeInfo)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.tabWidget_changeInfo.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem20)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem21)
        self.frame_17 = QtWidgets.QFrame(self.tab_6)
        self.frame_17.setStyleSheet("background-color:rgba(16, 30, 41, 240);\n"
                                    "border-radius:10px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        spacerItem22 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_24.addItem(spacerItem22)
        self.lineEdit_old_user = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_old_user.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                             "border:1px solid rgba(0, 0, 0, 0);\n"
                                             "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                             "color:rgb(255, 255, 255);\n"
                                             "padding-bottom:7px")
        self.lineEdit_old_user.setObjectName("lineEdit_old_user")
        self.verticalLayout_24.addWidget(self.lineEdit_old_user)
        spacerItem23 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_24.addItem(spacerItem23)
        self.lineEdit_old_pass = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_old_pass.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                             "border:1px solid rgba(0, 0, 0, 0);\n"
                                             "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                             "color:rgb(255, 255, 255);\n"
                                             "padding-bottom:7px")
        self.lineEdit_old_pass.setObjectName("lineEdit_old_pass")
        self.verticalLayout_24.addWidget(self.lineEdit_old_pass)
        spacerItem24 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_24.addItem(spacerItem24)
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_user.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                         "border:1px solid rgba(0, 0, 0, 0);\n"
                                         "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                         "color:rgb(255, 255, 255);\n"
                                         "padding-bottom:7px")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.verticalLayout_24.addWidget(self.lineEdit_user)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_24.addItem(spacerItem25)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_pass.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                         "border:1px solid rgba(0, 0, 0, 0);\n"
                                         "border-bottom-color:rgba(46, 82, 101, 255);\n"
                                         "color:rgb(255, 255, 255);\n"
                                         "padding-bottom:7px")
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.verticalLayout_24.addWidget(self.lineEdit_pass)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_24.addItem(spacerItem26)
        self.Btn_ChangePassUser = QtWidgets.QPushButton(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ChangePassUser.sizePolicy().hasHeightForWidth())
        self.Btn_ChangePassUser.setSizePolicy(sizePolicy)
        self.Btn_ChangePassUser.setMinimumSize(QtCore.QSize(0, 28))
        self.Btn_ChangePassUser.setBaseSize(QtCore.QSize(0, 0))
        self.Btn_ChangePassUser.setStyleSheet("QPushButton:pressed {    \n"
                                              "    background-color: rgba(85, 170, 255,0.5);\n"
                                              "}\n"
                                              "QPushButton{\n"
                                              "    color: rgb(0, 0, 0);\n"
                                              "    background-color: rgb(255, 255, 255);\n"
                                              "\n"
                                              "}")
        self.Btn_ChangePassUser.setObjectName("Btn_ChangePassUser")
        self.verticalLayout_24.addWidget(self.Btn_ChangePassUser)
        spacerItem27 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_24.addItem(spacerItem27)
        self.horizontalLayout_23.addLayout(self.verticalLayout_24)
        self.horizontalLayout_24.addWidget(self.frame_17)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem28)
        self.verticalLayout_25.addLayout(self.horizontalLayout_24)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem29)
        self.horizontalLayout_25.addLayout(self.verticalLayout_25)
        self.tabWidget_changeInfo.addTab(self.tab_6, "")
        self.horizontalLayout_13.addWidget(self.tabWidget_changeInfo)
        self.stackedWidget.addWidget(self.page_Setting)
        self.page_ClassList = QtWidgets.QWidget()
        self.page_ClassList.setObjectName("page_ClassList")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_ClassList)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_2 = QtWidgets.QFrame(self.page_ClassList)
        self.frame_2.setStyleSheet("background-color: rgb(40, 44, 52);\n"
                                   "")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem30 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem30)
        self.Btn_showList = QtWidgets.QPushButton(self.frame_2)
        self.Btn_showList.setStyleSheet("QPushButton:hover {    \n"
                                        "    color: rgb(210, 210, 210);\n"
                                        "    background-color: rgb(44, 49, 60);\n"
                                        "}\n"
                                        "QPushButton\n"
                                        "{\n"
                                        "\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px;\n"
                                        "    color: rgb(85, 170, 255);\n"
                                        "    background-color: rgb(52, 58, 71);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgba(85, 170, 255,0.5);\n"
                                        "    \n"
                                        "}")
        self.Btn_showList.setObjectName("Btn_showList")
        self.horizontalLayout_3.addWidget(self.Btn_showList)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem31)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem32)
        self.tableView_classList = QtWidgets.QTableView(self.frame_2)
        self.tableView_classList.setObjectName("tableView_classList")
        self.horizontalLayout_4.addWidget(self.tableView_classList)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem33)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem34)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem35 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem35)
        self.label_choiceClass = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        self.label_choiceClass.setFont(font)
        self.label_choiceClass.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_choiceClass.setObjectName("label_choiceClass")
        self.horizontalLayout.addWidget(self.label_choiceClass)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem36)
        self.label_CauseAbsent = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        self.label_CauseAbsent.setFont(font)
        self.label_CauseAbsent.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_CauseAbsent.setObjectName("label_CauseAbsent")
        self.horizontalLayout.addWidget(self.label_CauseAbsent)
        spacerItem37 = QtWidgets.QSpacerItem(220, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem37)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_class = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_class.setMaximumSize(QtCore.QSize(229, 16777215))
        self.comboBox_class.setStyleSheet("QComboBox{\n"
                                          "    background-color: rgb(27, 29, 35);\n"
                                          "    border-radius: 5px;\n"
                                          "    border: 2px solid rgb(27, 29, 35);\n"
                                          "    padding: 5px;\n"
                                          "    padding-left: 10px;\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "QComboBox:hover{\n"
                                          "    border: 2px solid rgb(64, 71, 88);\n"
                                          "}\n"
                                          "QComboBox QAbstractItemView {\n"
                                          "    color: rgb(85, 170, 255);    \n"
                                          "    background-color: rgb(27, 29, 35);\n"
                                          "    padding: 10px;\n"
                                          "    selection-background-color: rgb(39, 44, 54);\n"
                                          "}")
        self.comboBox_class.setObjectName("comboBox_class")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_class)
        spacerItem38 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem38)
        self.radioButton_present = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_present.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_present.setFont(font)
        self.radioButton_present.setStyleSheet("QRadioButton:hover{\n"
                                               "    border: 2px solid rgb(64, 71, 88);\n"
                                               "    border-radius: 5px;\n"
                                               "}\n"
                                               "QRadioButton{\n"
                                               "color: rgb(255, 255, 255);\n"
                                               "\n"
                                               "}\n"
                                               "")
        self.radioButton_present.setObjectName("radioButton_present")
        self.horizontalLayout_2.addWidget(self.radioButton_present)
        spacerItem39 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem39)
        self.radioButton_Absent = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_Absent.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_Absent.setFont(font)
        self.radioButton_Absent.setStyleSheet("QRadioButton:hover{\n"
                                              "    border: 2px solid rgb(64, 71, 88);\n"
                                              "    border-radius: 5px;\n"
                                              "    \n"
                                              "}\n"
                                              "QRadioButton{\n"
                                              "color: rgb(255, 255, 255);\n"
                                              "\n"
                                              "}\n"
                                              "")
        self.radioButton_Absent.setObjectName("radioButton_Absent")
        self.horizontalLayout_2.addWidget(self.radioButton_Absent)
        spacerItem40 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem40)
        self.lineEdit_Cause = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_Cause.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Cause.setMaximumSize(QtCore.QSize(330, 16777215))
        self.lineEdit_Cause.setStyleSheet("background-color: rgb(27, 29, 35);\n"
                                          "border-radius: 5px;\n"
                                          "padding: 10px;\n"
                                          "color: rgb(255, 255, 255);")
        self.lineEdit_Cause.setObjectName("lineEdit_Cause")
        self.horizontalLayout_2.addWidget(self.lineEdit_Cause)
        spacerItem41 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem41)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem42 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem42)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem43)
        self.Btn_AccepStatus = QtWidgets.QPushButton(self.frame_2)
        self.Btn_AccepStatus.setStyleSheet("QPushButton:hover {    \n"
                                           "    color: rgb(210, 210, 210);\n"
                                           "    background-color: rgb(44, 49, 60);\n"
                                           "}\n"
                                           "QPushButton\n"
                                           "{\n"
                                           "\n"
                                           "    border-radius: 5px;\n"
                                           "    padding: 5px;\n"
                                           "    color: rgb(85, 170, 255);\n"
                                           "    background-color: rgb(52, 58, 71);\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: rgba(85, 170, 255,0.5);\n"
                                           "    \n"
                                           "}")
        self.Btn_AccepStatus.setObjectName("Btn_AccepStatus")
        self.horizontalLayout_8.addWidget(self.Btn_AccepStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem44)
        self.horizontalLayout_12.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_ClassList)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_Date = QtWidgets.QLabel(self.frame_3)
        self.label_Date.setMinimumSize(QtCore.QSize(70, 0))
        self.label_Date.setMaximumSize(QtCore.QSize(163, 70))
        self.label_Date.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_Date.setObjectName("label_Date")
        # self.horizontalLayout_7.addWidget(self.label_Date, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        spacerItem45 = QtWidgets.QSpacerItem(700, 8, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem45)
        self.label_Version = QtWidgets.QLabel(self.frame_3)
        self.label_Version.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        self.label_Version.setFont(font)
        self.label_Version.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_Version.setObjectName("label_Version")
        # self.horizontalLayout_7.addWidget(self.label_Version, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        spacerItem46 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem46)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget_changeInfo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #########################icons#####################
        self.Btn_Menu.setIcon(QIcon("icons/20x20/cil-menu.png"))
        self.Btn_Menu.setIconSize(QSize(64, 64))
        self.Btn_classList.setIcon(QIcon("icons/16x16/cil-clipboard.png"))
        self.Btn_classList.setIconSize(QSize(64, 64))
        self.Btn_Settings.setIcon(QIcon("icons/16x16/cil-settings.png"))
        self.Btn_Settings.setIconSize(QSize(64, 64))
        self.Btn_min.setIcon(QIcon("icons/24x24/cil-window-minimize.png"))
        self.Btn_max.setIcon(QIcon("icons/24x24/cil-window-maximize.png"))
        self.Btn_close.setIcon(QIcon("icons/24x24/cil-x.png"))
        self.Btn_Home.setIcon(QIcon("icons/16x16/cil-home.png"))
        pixmap = QPixmap('icons/uni/Isfahan_uni.png')
        self.label_Picture.setPixmap(pixmap)

        #########################pages########################
        self.Btn_Settings.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_Setting))
        self.Btn_Home.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_Home))
        self.Btn_classList.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_ClassList))

        #########################Action#######################
        self.Btn_close.clicked.connect(MainWindow.close)
        self.Btn_max.clicked.connect(MainWindow.showMaximized)
        self.Btn_min.clicked['bool'].connect(MainWindow.showMinimized)
        # self.Btn_Accept_add.clicked.connect(self.addProfessor)

        ###################date##################### ******************************************
        # self.label_Date.setText(str(jdatetime.date.today()))
        self.lineEdit_old_pass

    # data base
    # def addProfessor(self):
    #     try:
    #         mydb = mc.connect(
    #             host="localhost",
    #             user="root",
    #             password="",
    #             database="setstatus"
    #         )
    #         mycursor = mydb.cursor()
    #
    #         nameProfessor = self.lineEdit_namePro_add.text()
    #         nameCourse = self.lineEdit_nameStudy_add.text()
    #         Days = self.lineEdit_Days_add.text()
    #         Time = self.lineEdit_time_add.text()
    #
    #         query = "INSERT INTO professors (nameprofessor, nameofcourse, days, time) VALUES (%s, %s, %s, %s)"
    #         value = (nameProfessor, nameCourse, Days, Time)
    #
    #         mycursor.execute(query, value)
    #         mydb.commit()
    #
    #     except mc.Error as e:
    #         self.label_4.setText("Error")
    #         self.label_3.setText("Error")
    #         self.label_2.setText("Error")
    #         self.label_5.setText("Error")

    # def showClassList(self):
    #     dbname = "setstatus"
    #     tblname = "professors"
    #     try:
    #         mydb = mc.connect(
    #             host="localhost",
    #             user="root",
    #             password="",
    #             database=dbname
    #         )
    #         mycursor = mydb.cursor()
    #         mycursor.execute("SELECT * FROM {}".format(tblname))
    #         result = mycursor.fetchall()
    #         self.tableWidget_add.setRowCount(0)
    #         for row_number, row_date in enumerate(result):
    #             self.tableWidget_add.insertRow(row_number)
    #             for column_number, data in enumerate(row_date):
    #                 self.tableWidget_add.setItem(row_number, column_number, QTableWidgetItem(str(data)))
    #     except mc.Error as e:
    #         print("Error occured")

    # def addProfessor(self):
    #     mydb = mysql.connector.connect(
    #         host="localhost",
    #         user="root",
    #         password="",
    #         database="setstatus"
    #     )
    #     nameProfessor = self.lineEdit_namePro_add.text()
    #     nameCourse = self.lineEdit_nameStudy_add.text()
    #     Days = self.lineEdit_Days_add.text()
    #     Time = self.lineEdit_time_add.text()
    #     mycursor = mydb.cursor()
    #     sql = "INSERT INTO  (nameprofessor, nameofcourse, days, time) VALUES (%s, %s, %s, %s)"
    #     val = (nameProfessor, nameCourse, Days, Time)
    #     mycursor.execute(sql, val)
    #     mydb.commit()
    #     print(mycursor.rowcount, "details inserted")
    #     # disconnecting from server
    #     mydb.close()

    # def db_connect(self):
    #     try:
    #         mydb = mc.connect(
    #             host="localhost",
    #             user="root",
    #             password="",
    #             database="setstatus"
    #         )
    #
    #         self.label_2.setText(" connection")
    #
    #     except mc.Error as e:
    #         self.label_2.setText("Error ")

    ############   DATA BASE   ############
    # {
    #
    # def addProfessor(self):
    #     db = DB()
    #     db.create_all_table()
    #     db.create_session()
    #     namePro = self.lineEdit_namePro_add.text()
    #     addProfessor = db.Professor(firstname=namePro)
    #





    #}
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Application.setText(_translate("MainWindow", "Set Status"))
        self.label_Home.setText(_translate("MainWindow", " Page Home"))
        self.Btn_showList_add.setText(_translate("MainWindow", "show List"))
        item = self.tableWidget_add.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_add.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name Professor"))
        item = self.tableWidget_add.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name Course"))
        item = self.tableWidget_add.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Days"))
        item = self.tableWidget_add.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "time"))
        self.label_2.setText(_translate("MainWindow", "Name Professor"))
        self.label_3.setText(_translate("MainWindow", "Name Study"))
        self.label_4.setText(_translate("MainWindow", "Days"))
        self.label_5.setText(_translate("MainWindow", "Times"))
        self.Btn_Accept_add.setText(_translate("MainWindow", "Accept"))
        self.tabWidget_changeInfo.setTabText(self.tabWidget_changeInfo.indexOf(self.Add_Professor),
                                             _translate("MainWindow", "Add Professor"))
        self.Btn_showList_rm.setText(_translate("MainWindow", "show List"))
        item = self.tableWidget_rm.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_rm.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name Professor"))
        item = self.tableWidget_rm.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name Study"))
        item = self.tableWidget_rm.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Days"))
        item = self.tableWidget_rm.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "time"))
        self.label_6.setText(_translate("MainWindow", "Id :"))
        self.checkBox_rm.setText(_translate("MainWindow", "Are you sure you want to delete this master?"))
        self.Btn_Accept_rm.setText(_translate("MainWindow", "Accept"))
        self.tabWidget_changeInfo.setTabText(self.tabWidget_changeInfo.indexOf(self.remove_professor),
                                             _translate("MainWindow", "Remove Professor"))
        self.Btn_showList_changeInfo.setText(_translate("MainWindow", "show List"))
        item = self.tableWidget_changeInfo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_changeInfo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name Professor"))
        item = self.tableWidget_changeInfo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name Study"))
        item = self.tableWidget_changeInfo.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Days"))
        item = self.tableWidget_changeInfo.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "time"))
        self.label_11.setText(_translate("MainWindow", "id"))
        self.label_7.setText(_translate("MainWindow", "Name Professor"))
        self.label_8.setText(_translate("MainWindow", "Name Study"))
        self.label_9.setText(_translate("MainWindow", "Days"))
        self.label_10.setText(_translate("MainWindow", "Times"))
        self.checkBox_changeInfo.setText(_translate("MainWindow", "Are you sure you want to change this master?"))
        self.Btn_Accept_changeInfo.setText(_translate("MainWindow", "Accept"))
        self.tabWidget_changeInfo.setTabText(self.tabWidget_changeInfo.indexOf(self.tab_5),
                                             _translate("MainWindow", "Change Information"))
        self.lineEdit_old_user.setPlaceholderText(_translate("MainWindow", "  Confirm User name"))
        self.lineEdit_old_pass.setPlaceholderText(_translate("MainWindow", "  Confirm Password"))
        self.lineEdit_user.setPlaceholderText(_translate("MainWindow", "New Username"))
        self.lineEdit_pass.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.Btn_ChangePassUser.setText(_translate("MainWindow", "change"))
        self.tabWidget_changeInfo.setTabText(self.tabWidget_changeInfo.indexOf(self.tab_6),
                                             _translate("MainWindow", "Change Password"))
        self.Btn_showList.setText(_translate("MainWindow", "show "))
        self.label_choiceClass.setText(_translate("MainWindow", "Choice Class"))
        self.label_CauseAbsent.setText(_translate("MainWindow", "Cause"))
        self.comboBox_class.setItemText(0, _translate("MainWindow", "physic_1"))
        self.comboBox_class.setItemText(1, _translate("MainWindow", "Computer_Workshop"))
        self.comboBox_class.setItemText(2, _translate("MainWindow", "data_structures"))
        self.comboBox_class.setItemText(3, _translate("MainWindow", "labratory"))
        self.comboBox_class.setItemText(4, _translate("MainWindow", "analys and Desing Divices"))
        self.comboBox_class.setItemText(5, _translate("MainWindow", "archetecture computer"))
        self.comboBox_class.setItemText(6, _translate("MainWindow", "desing Algoritm"))
        self.radioButton_present.setText(_translate("MainWindow", "Present"))
        self.radioButton_Absent.setText(_translate("MainWindow", "Absent"))
        self.Btn_AccepStatus.setText(_translate("MainWindow", "Accept"))
        self.label_Date.setText(_translate("MainWindow", "Thursday, Esfand 26, 1400 AP"))
        self.label_Version.setText(_translate("MainWindow", "v1.0.0"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
